apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  namespace: mern-app
type: Opaque
data:
  connectionString: bW9uZ29kYjovL2FkbWluOm1vbmdvZGJfcGFzc3dvcmRAbW9uZ29kYi1zZXJ2aWNlOjI3MDE3L21lcm4tYXBwP2F1dGhTb3VyY2U9YWRtaW4=
  username: YWRtaW4= #admin
  password: bW9uZ29kYl9wYXNzd29yZA== #mongodb_password