apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  namespace: mern-app
type: Opaque
data:
  connectionString: bW9uZ29kYjovL21vbmdvZGJfdXNlcjptb25nb2RiX3Bhc3N3b3JkQG1vbmdvZGItc2VydmljZToyNzAxNy9tZXJuLWFwcD9hdXRoU291cmNlPWFkbWlu # Connection string
  username: bW9uZ29kYl91c2Vy            # mongdb_user
  password: bW9uZ29kYl9wYXNzd29yZA==    # mongdb_password